### ISSUE TITLE
META-ID: Store and return raw `username` value

### ISSUE THREAD

**Issue by lukehedger** [meta-network/go-meta#53]
### Problem
The raw `username` of a META-ID is required for display purposes.

### Use case 1
An application has a page that displays data about a META-ID, including the claims made **about** that ID. With the current API the application would only be able to represent the `issuer` of the claim by the address, which is not immediately useful to a human user.

### Use case 2
An application has a page that displays data about a META-ID, including the claims made **by** that ID. With the current API the application would only be able to represent the `subject` of the claim by the address, which is not immediately useful to a human user.

### Solution
One option is to pass the raw `username` to the API when creating an identity. This value will then be stored with the identity and returned when requested:
```
mutation createIdentityMutation($username: String!, $usernameHash: String!, $owner: String!, $signature: String!) {
  createIdentity(
    username: $username,
    usernameHash: $usernameHash,
    owner: $owner,
    signature: $signature
  ) {
    id
    signature
    owner
    username
  }
}
```

A META-ID's `username` could then be retrieved using the `identity` query:
```
query getIdentity($owner: String!) {
  identity(owner: $owner) {
    id
    owner
    signature
    username
  }
}
```

Ideally, the `claim` query would return `issuerUsername` and `subjectUsername`.

```
claim (issuer: $issuer) {
  id
  issuer,
  issuerUsername,
  subject
  subjectUsername,
  claim
}
```

This would fit both use cases 🎉. But, if this is not possible, the client can recursively fetch each issuer's `identity` - although this is pretty inefficient at scale.

**Comment by lmars** [comment]
We should add `username` to the `identity` table and expose via the API :+1:
