### ISSUE TITLE
META-ID: Add `filter` param to `claim` query

### ISSUE THREAD

**Issue by lukehedger** [meta-network/go-meta#54]
### Problem
With the current API, it is not possible to write a **single** query that could accept **either** an `issuer` variable or a `subject` variable. It is therefore necessary to construct two separate queries with different variables.

For example, this query:
```
query readClaims($issuer: String, $subject: String) {
  claim (issuer: $issuer) {
    id
    issuer
    subject
    claim
  }
}
```
would return:
```
{
  "errors": [
    {
      "message": "Variable \"$subject\" is never used in operation \"readClaims\".",
    }
  ]
}
```

### Use case
A JavaScript service that exposes a generic interface for making META Network GraphQL requests, which allows consumers of the service to simply provide query parameters without writing the underlying GraphQL query.

(pseudo-code used to demonstrate desired function signature)
```
const readClaims = (variables={ issuer || subject }) => metaNetworkRequest(`
  query readClaims($issuer: String || $subject: String) {
    claim (issuer: $issuer || subject: $subject) {
      id
      issuer
      subject
      claim
    }
  }
`, variables)
```

### Solution
Add a `filter` param that accepts either `issuer` or `subject` or a combination of the two (along with the other possible variables)!

This would enable a query like so:
```
query readClaims($filter: Filter) {
  claim (filter: $filter) {
    id
    issuer
    subject
    claim
  }
}
```

And the JS service would look something like this:
```
const readClaims = (variables={ filter: { issuer, subject } }) => metaNetworkRequest(`
  query readClaims($fitler: Filter) {
    claim (filter: $filter) {
      id
      issuer
      subject
      claim
    }
  }
`, variables)
```

[See this for reference.](https://blog.graph.cool/designing-powerful-apis-with-graphql-query-parameters-8c44a04658a9)

The `Filter` schema definition could look something like this:
```
input Filter {
  claim: String
  issuer: String
  signature: String
  subject: String
}
```

**Comment by lmars** [comment]
SGTM :+1:
