### ISSUE TITLE
META-ID: Prevent an address from creating multiple IDs

### ISSUE THREAD

**Issue by lukehedger** [meta-network/go-meta#56]
An Ethereum address should only be the `owner` for a single META-ID.

If this address is used to create a second identity an error should be returned.

See [discussion in Slack](https://jaakmein.slack.com/archives/C54DGRMFZ/p1512406914000682).

**Comment by MrTibbles** [comment]
Should it not simply fire `readIdentityByOwner` prior to attempting to create one, rather than throwing an error. 
So it would then inform the user that they have already created an identity with account, and log them in?

**Comment by lukehedger** [comment]
@MrTibbles As discussed this flow could be used in an application to prevent multiple IDs with the same owner but we'd still need a check on the API as it will be a public API accessible via UIs and programmatically.

**Comment by lmars** [comment]
This can be enforced in the SQL schema using a unique index.
