### ISSUE TITLE
META-ID: Proposal to add reference to additional identity data

### ISSUE THREAD

**Issue by lukehedger** [meta-network/go-meta#57]
A requirement for the META-ID dapp UI is to display additional data about an individual, such as name, image and web address.

Initial thought is this would be a stored as a reference to a Swarm location in the META Identity database.

Something like:
```
{
  profile: 'f8fd38fcdd90c667cbf25b4011686d64a49e822d04851858129ae8610e921f13'
  ...
}
```

![meta-id-dapp-search](https://user-images.githubusercontent.com/1913316/34037054-403b5120-e17f-11e7-9588-0da50929ba8b.png)

**Comment by lmars** [comment]
Could this just be a self-signed claim? For example:

```json
{
  "issuer":   "0x1234",
  "subject":  "0x1234",
  "property": "profile.image",
  "claim":    "0xf8fd38fcdd90c667cbf25b4011686d64a49e822d04851858129ae8610e921f13"
}
```

Then we treat the claim value as the Swarm hash of an image?

**Comment by lukehedger** [comment]
@lmars yes, great idea! Will close in favour of adding a method to generate these 'profile' claims to https://github.com/meta-network/meta.js.

**Comment by nolash** [comment]
Will we also allow adding profile data that's not strictly verifiable? As in vanity data? If so, treating them as "claims" would maybe not be semantically correct.

**Comment by lmars** [comment]
@nolash everything is verifiable, I can make a self signed claim which verifies that I said that this is my profile data, rather than someone else right?

**Comment by nolash** [comment]
It is true, but self-signing that kills trees
